env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:vue/vue3-essential
  - plugin:@typescript-eslint/recommended
  - '@vue/eslint-config-typescript'
overrides: []
parser: 'vue-eslint-parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  parser:
    ts: '@typescript-eslint/parser'
plugins:
  - vue
  - '@typescript-eslint'
rules: {}
